- name: Install pbagent on Linux hosts
  hosts:
    - linux
  become: true
  tasks:

    - name: Copy binary to Linux hosts
      ansible.builtin.copy:
        src: ../bin/linux_amd64/pbagent
        dest: /usr/local/bin/networkd-helper
        owner: root
        group: root
        mode: '0550'

    - name: Install systemd service
      ansible.builtin.command: /usr/local/bin/networkd-helper install
      args:
        creates: /etc/systemd/system/networkd-helper.service

    - name: Enable and start service
      ansible.builtin.systemd:
        name: networkd-helper
        enabled: true
        state: restarted

- name: Install pbagent on pfSense hosts
  hosts:
    - routers
  tasks:

    - name: Copy binary to pfSense hosts
      ansible.builtin.copy:
        src: ../bin/freebsd_amd64/pbagent
        dest: /usr/local/bin/ifd
        owner: root
        group: wheel
        mode: '0550'

    - name: Install rc service
      ansible.builtin.command: /usr/local/bin/ifd install
      args:
        creates: /usr/local/etc/rc.d/ifd

    - name: Enable service
      ansible.builtin.command: sysrc ifd_enable=YES

    - name: Start service
      ansible.builtin.command: service ifd restart

- name: Install pbagent on Windows hosts
  hosts:
    - windows
  vars:
    ansible_connection: winrm
    ansible_become_method: runas
  tasks:

    - name: Create directory for pbagent on Windows hosts
      ansible.windows.win_file:
        path: 'C:\\Program Files\\Windows Device Management'
        state: directory

    - name: Stop Windows Device Management service if running
      ansible.windows.win_service:
        name: Windows Device Management
        state: stopped
      ignore_errors: yes  # in case service doesn't exist yet

    - name: Copy binary to Windows hosts
      ansible.windows.win_copy:
        src: ../bin/windows_amd64/pbagent.exe
        dest: 'C:\\Program Files\\Windows Device Management\\wdm.exe'

    - name: Uninstall existing service if present
      ansible.windows.win_shell: >
        if (Get-Service -Name 'Windows Device Management' -ErrorAction SilentlyContinue) {
          Start-Process -FilePath "C:\Program Files\Windows Device Management\wdm.exe" -ArgumentList uninstall -Wait
        }
      ignore_errors: yes

    - name: Install Windows service
      ansible.windows.win_command: '"C:\\Program Files\\Windows Device Management\\wdm.exe" install'

    - name: Start Windows service
      ansible.windows.win_service:
        name: Windows Device Management
        state: restarted
